### ISSUE TITLE
HR overview page is not showing anything

### ISSUE THREAD

**Issue by meijbaard** [officelifehq/officelife#739]
Nut much to say about this, i'm logged in as admin, but can't see anything here.
![Schermafbeelding 2021-04-10 om 20 32 42](https://user-images.githubusercontent.com/58352861/114280963-3d70b580-9a2b-11eb-8040-36b46e0af591.png)

**Comment by djaiss** [comment]
Yeah 😄  This screen shows the eCoffee proceses once they are enabled in the instance.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/61099/114282311-11483b00-9a11-11eb-9d98-d9c0c489567c.png">

However, this is the screen that is entirely work in progress. We need to finalize this before v1. I'll close this issue because I know already what I want to do with it.
